ломаем тесты

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -21,4 +21,9 @@ jobs:
         run: npm install
 
       - name: Run tests
-        run: npm test
+        run: |
+          npm test
+          if [ $? -ne 0 ]; then
+            echo "Tests failed!"
+            exit 1
+          fi
